<div class="profile-image"></div>
<h3 class="title-details">Nir Goldman <br/> Magento Developer</h3>
<p class="before-end detailtext">
    Magento developer passionate about solving daily challenges, with experience in the latest web technologies.
    Multi-Discipline, excellent interpersonal skills, fast and self-learner, great team player, hard worker, built several projects.
</p>
<p class="detailtext">Contact me for development suppot : <a href="tel:+972586275326">+972586275326</a></p>